#!/usr/bin/env python3
"""Bidirectional lookup over the note ↔ terminology mapping.

Each note under ``terminologies/notes/`` has a ``### Key terminologies``
section — a bullet list of ``- **Term** — definition`` lines. This module
parses those term names and keeps a two-way index:

    note      -> [terminologies it defines]
    terminology -> [notes that define it]

On disk the mapping persists compactly at ``notes_terminologies_mapping.json``
as ``{ "<note filename>": ["Term A", "Term B", ...] }``. The known prefix
``terminologies/notes/`` is held as a constant and reattached on load, so the
public API still takes and returns *full* project-root-relative paths. The
reverse map (terminology -> notes) is built in memory at load time.

`rebuild` / `sync` / `remove` also regenerate two artifacts:
  - ``index.md`` — the human-readable master list of every terminology.
  - ``terminologies/glossary/<slug>.md`` — one **standalone** page per
    terminology (title + definition only; no link to any note). The note ↔
    terminology relationship lives solely in this mapping JSON.

Usage (Python):
    from mapping import NotesTerminologyMapping
    m = NotesTerminologyMapping.load()
    m.terminologies_for("terminologies/notes/260604_vllm.md")
    m.notes_for("KV cache (Key–Value cache)")

Usage (CLI):
    python terminologies/index/mapping.py terminologies <note>
    python terminologies/index/mapping.py notes "<terminology>"
    python terminologies/index/mapping.py list
    python terminologies/index/mapping.py glossary
    python terminologies/index/mapping.py sync <note>
    python terminologies/index/mapping.py remove <note>
    python terminologies/index/mapping.py rebuild
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parents[2]
INDEX_DIR = Path(__file__).resolve().parent
MAPPING_FILENAME = "notes_terminologies_mapping.json"
INDEX_MD_FILENAME = "index.md"

NOTES_PREFIX = "terminologies/notes/"
GLOSSARY_DIR_REL = "terminologies/glossary"

# Marker line for the generated master list (index.md). Glossary pages are
# deliberately standalone and carry no such marker.
GENERATED_MARKER = "_Auto-generated by `mapping.py` — do not edit by hand._"

# A "- **Term** — definition" bullet: bold span is the term, the rest of the
# line (after an optional dash / colon separator) is the definition.
TERM_BULLET_RE = re.compile(
    r"^\s*[-*]\s+\*\*(.+?)\*\*\s*(?:[—–:-]\s*)?(.*)$"
)
# Headings that bound the "Key terminologies" section.
HEADING_RE = re.compile(r"^#{1,6}\s+(.*)$")
KEY_TERMS_HEADING = "key terminologies"


def _mapping_path() -> Path:
    return INDEX_DIR / MAPPING_FILENAME


def _index_md_path() -> Path:
    return INDEX_DIR / INDEX_MD_FILENAME


def _glossary_dir() -> Path:
    return PROJECT_ROOT / GLOSSARY_DIR_REL


def _slug(term: str) -> str:
    """Filename-safe slug for a terminology, e.g.
    'KV cache (Key–Value cache)' -> 'kv_cache_key_value_cache'."""
    return re.sub(r"[^a-z0-9]+", "_", term.lower()).strip("_")


def _notes_root() -> Path:
    return PROJECT_ROOT / NOTES_PREFIX


def _split_note(full_path: str) -> str:
    if not full_path.startswith(NOTES_PREFIX):
        raise ValueError(f"note path missing prefix: {full_path!r}")
    return full_path[len(NOTES_PREFIX):]


def _join_note(filename: str) -> str:
    return NOTES_PREFIX + filename


def _normalize_note(path: str) -> str:
    """Accept an absolute path, a bare filename, or a full rel path."""
    p = Path(path)
    if p.is_absolute():
        try:
            return p.resolve().relative_to(PROJECT_ROOT).as_posix()
        except ValueError as exc:
            raise SystemExit(f"path is outside project root: {path}") from exc
    if "/" not in path:
        return _join_note(path)
    return p.as_posix()


def parse_terminology_entries(note_full_path: str) -> List[Tuple[str, str]]:
    """Extract (term, definition) pairs from a note's '### Key terminologies'
    section. Reads bullet lines until the next heading. Order is preserved;
    exact-duplicate terms within one note are dropped.
    """
    full = PROJECT_ROOT / note_full_path
    if not full.exists():
        raise SystemExit(f"file not found: {full}")
    entries: List[Tuple[str, str]] = []
    seen: set[str] = set()
    in_section = False
    for line in full.read_text(encoding="utf-8").splitlines():
        heading = HEADING_RE.match(line)
        if heading:
            in_section = heading.group(1).strip().lower() == KEY_TERMS_HEADING
            continue
        if not in_section:
            continue
        m = TERM_BULLET_RE.match(line)
        if m:
            term = m.group(1).strip()
            definition = m.group(2).strip()
            if term and term not in seen:
                seen.add(term)
                entries.append((term, definition))
    return entries


def parse_terminologies(note_full_path: str) -> List[str]:
    """Term names only — see parse_terminology_entries for definitions."""
    return [term for term, _ in parse_terminology_entries(note_full_path)]


class NotesTerminologyMapping:
    """Two-way index over (note_path, terminology) pairs."""

    def __init__(self, by_note: Dict[str, List[str]]) -> None:
        self._by_note: Dict[str, List[str]] = {
            note: list(terms) for note, terms in by_note.items()
        }
        self._rebuild_reverse()

    def _rebuild_reverse(self) -> None:
        rev: Dict[str, List[str]] = defaultdict(list)
        for note, terms in self._by_note.items():
            for term in terms:
                rev[term].append(note)
        self._by_term: Dict[str, List[str]] = {
            term: sorted(set(notes)) for term, notes in rev.items()
        }

    # ---- persistence ---------------------------------------------------

    @classmethod
    def load(cls, path: Path | None = None) -> "NotesTerminologyMapping":
        path = path or _mapping_path()
        if not path.exists():
            return cls({})
        raw = json.loads(path.read_text(encoding="utf-8"))
        return cls({_join_note(name): terms for name, terms in raw.items()})

    def save(self, path: Path | None = None) -> None:
        path = path or _mapping_path()
        out = {
            _split_note(note): self._by_note[note]
            for note in sorted(self._by_note)
        }
        path.write_text(
            json.dumps(out, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    def write_index_md(self, path: Path | None = None) -> None:
        """Regenerate the human-readable master list of terminologies.

        Each term links to its per-term page under ``terminologies/glossary/``.
        """
        path = path or _index_md_path()
        lines = [
            "# Terminologies Index",
            "",
            GENERATED_MARKER,
            "",
            f"{len(self.terminologies)} terminologies across "
            f"{len(self._by_note)} notes.",
            "",
        ]
        for term in self.terminologies:
            notes = ", ".join(
                f"`{_split_note(n)}`" for n in self.notes_for(term)
            )
            link = f"../glossary/{_slug(term)}.md"
            lines.append(f"- [**{term}**]({link}) — {notes}")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def write_glossary(self, glossary_dir: Path | None = None) -> int:
        """Regenerate one **standalone** page per terminology under glossary/.

        Each page is self-contained: the term as its H1 title and its
        definition(s). It carries no back-link to any note and no generator
        marker — the note ↔ terminology relationship lives solely in
        ``notes_terminologies_mapping.json``. Definitions are pulled from the
        defining notes only at generation time. The glossary folder is owned
        by this generator: any ``*.md`` not matching a current term is pruned.
        Returns the number of pages written.
        """
        out_dir = glossary_dir or _glossary_dir()
        out_dir.mkdir(parents=True, exist_ok=True)

        written: set[str] = set()
        for term in self.terminologies:
            defs: List[str] = []
            for note in self.notes_for(term):
                for t, d in parse_terminology_entries(note):
                    if t == term and d and d not in defs:
                        defs.append(d)
            lines = [f"# {term}", ""]
            if len(defs) == 1:
                lines.append(defs[0])
            else:  # zero defs -> title only; multiple -> bulleted
                lines.extend(f"- {d}" for d in defs)
            (out_dir / f"{_slug(term)}.md").write_text(
                "\n".join(lines).rstrip() + "\n", encoding="utf-8"
            )
            written.add(f"{_slug(term)}.md")

        for stale in out_dir.glob("*.md"):
            if stale.name not in written:
                stale.unlink()
        return len(written)

    # ---- queries -------------------------------------------------------

    def terminologies_for(self, note_path: str) -> List[str]:
        return list(self._by_note.get(note_path, []))

    def notes_for(self, terminology: str) -> List[str]:
        return list(self._by_term.get(terminology, []))

    @property
    def terminologies(self) -> List[str]:
        """The master list — every terminology, sorted, case-insensitive."""
        return sorted(self._by_term, key=str.casefold)

    @property
    def notes(self) -> List[str]:
        return sorted(self._by_note)

    # ---- mutations -----------------------------------------------------

    def sync(self, note_path: str) -> List[str]:
        """Re-parse one note and replace its terminology list."""
        _split_note(note_path)  # validate prefix
        terms = parse_terminologies(note_path)
        if terms:
            self._by_note[note_path] = terms
        else:
            self._by_note.pop(note_path, None)
        self._rebuild_reverse()
        return terms

    def remove(self, note_path: str) -> None:
        if note_path not in self._by_note:
            raise SystemExit(f"not in mapping: {note_path}")
        del self._by_note[note_path]
        self._rebuild_reverse()


# ---- CLI ---------------------------------------------------------------


def _print_lines(lines: Iterable[str]) -> None:
    lines = list(lines)
    if not lines:
        print("(no matches)")
        return
    for line in lines:
        print(line)


def _cmd_terminologies(args: argparse.Namespace) -> None:
    m = NotesTerminologyMapping.load()
    _print_lines(m.terminologies_for(_normalize_note(args.note)))


def _cmd_notes(args: argparse.Namespace) -> None:
    m = NotesTerminologyMapping.load()
    _print_lines(m.notes_for(args.terminology))


def _cmd_list(args: argparse.Namespace) -> None:
    m = NotesTerminologyMapping.load()
    _print_lines(m.terminologies)


def _cmd_glossary(args: argparse.Namespace) -> None:
    m = NotesTerminologyMapping.load()
    n = m.write_glossary()
    print(f"wrote {n} glossary pages to {GLOSSARY_DIR_REL}/")


def _cmd_sync(args: argparse.Namespace) -> None:
    m = NotesTerminologyMapping.load()
    note = _normalize_note(args.note)
    terms = m.sync(note)
    m.save()
    m.write_index_md()
    m.write_glossary()
    print(f"synced {note}: {len(terms)} terminologies")


def _cmd_remove(args: argparse.Namespace) -> None:
    m = NotesTerminologyMapping.load()
    note = _normalize_note(args.note)
    m.remove(note)
    m.save()
    m.write_index_md()
    m.write_glossary()
    print(f"removed {note} from mapping")


def _cmd_rebuild(args: argparse.Namespace) -> None:
    by_note: Dict[str, List[str]] = {}
    notes = sorted(_notes_root().glob("*.md"))
    for p in notes:
        rel = p.relative_to(PROJECT_ROOT).as_posix()
        terms = parse_terminologies(rel)
        if terms:
            by_note[rel] = terms
    m = NotesTerminologyMapping(by_note)
    m.save()
    m.write_index_md()
    m.write_glossary()
    print(f"mapped {len(by_note)} notes, {len(m.terminologies)} terminologies")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Bidirectional note ↔ terminology lookup."
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_t = sub.add_parser("terminologies", help="list terminologies in a note")
    p_t.add_argument("note", help="e.g. terminologies/notes/260604_vllm.md")
    p_t.set_defaults(func=_cmd_terminologies)

    p_n = sub.add_parser("notes", help="list notes that define a terminology")
    p_n.add_argument("terminology", help='e.g. "KV cache (Key–Value cache)"')
    p_n.set_defaults(func=_cmd_notes)

    p_l = sub.add_parser("list", help="print the master list of terminologies")
    p_l.set_defaults(func=_cmd_list)

    p_g = sub.add_parser(
        "glossary", help="regenerate per-term pages under terminologies/glossary/"
    )
    p_g.set_defaults(func=_cmd_glossary)

    p_s = sub.add_parser("sync", help="re-parse one note into the mapping")
    p_s.add_argument("note")
    p_s.set_defaults(func=_cmd_sync)

    p_rm = sub.add_parser("remove", help="drop a note from the mapping")
    p_rm.add_argument("note")
    p_rm.set_defaults(func=_cmd_remove)

    p_rb = sub.add_parser("rebuild", help="re-parse all notes from disk")
    p_rb.set_defaults(func=_cmd_rebuild)

    return parser


def main(argv: Iterable[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc


if __name__ == "__main__":
    main()
