#!/usr/bin/env python3
"""Word-level IPA lookup against the ground-truth dictionary vocab/US_IPA.json.

The dictionary is a flat JSON object {lowercase-word: bare-IPA} (no slashes),
holding the citation form of each word, e.g. {"walk": "wɑːk", "to": "tuː"}.
It is the single source of truth: per-word IPA is taken from here first, and
only words missing from it are generated by the model and merged back in.

Usage:
  python ipa_lookup.py missing <story_or_text_file> [dict.json]
      Tokenize the file into words, normalize to dictionary-key form, and print
      a JSON report {"found": {word: ipa, ...}, "missing": [word, ...]} in
      first-occurrence order. `found` already gives you the authoritative IPA;
      `missing` is the list the model must generate.

  python ipa_lookup.py merge <new_pairs.json|-> [dict.json]
      Merge a JSON object {word: ipa} of newly generated entries into the
      dictionary. Existing keys are NEVER overwritten (they are ground truth);
      new words are appended. Pass "-" to read the pairs JSON from stdin.
      Writes the dictionary back as UTF-8, 2-space indent, trailing newline.

Default dict path is vocab/US_IPA.json (relative to the current directory).
Numbers and times (e.g. "8:55") are ignored — only alphabetic words, with
internal apostrophes/hyphens kept, are tokenized (minh's, you'll, twelve-floor).
"""
import json
import re
import sys
from collections import OrderedDict

DEFAULT_DICT = "vocab/US_IPA.json"
TOKEN_RE = re.compile(r"[A-Za-z]+(?:['\-][A-Za-z]+)*")


def load_dict(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f, object_pairs_hook=OrderedDict)


def tokenize(text):
    """Distinct lowercase word tokens in first-occurrence order."""
    text = text.replace("’", "'")  # curly apostrophe -> straight
    out, seen = [], set()
    for m in TOKEN_RE.finditer(text):
        w = m.group(0).lower()
        if w not in seen:
            seen.add(w)
            out.append(w)
    return out


def cmd_missing(args):
    if not args:
        sys.exit("missing: need <story_or_text_file>")
    text_path = args[0]
    dict_path = args[1] if len(args) > 1 else DEFAULT_DICT
    with open(text_path, encoding="utf-8") as f:
        text = f.read()
    d = load_dict(dict_path)
    found, missing = OrderedDict(), []
    for w in tokenize(text):
        if w in d:
            found[w] = d[w]
        else:
            missing.append(w)
    print(json.dumps({"found": found, "missing": missing},
                     ensure_ascii=False, indent=2))


def cmd_merge(args):
    if not args:
        sys.exit("merge: need <new_pairs.json|->")
    pairs_path = args[0]
    dict_path = args[1] if len(args) > 1 else DEFAULT_DICT
    raw = sys.stdin.read() if pairs_path == "-" else open(
        pairs_path, encoding="utf-8").read()
    new = json.loads(raw, object_pairs_hook=OrderedDict)
    d = load_dict(dict_path)
    added = 0
    for w, ipa in new.items():
        w = w.lower()
        if w not in d:  # never overwrite existing ground truth
            d[w] = ipa
            added += 1
    with open(dict_path, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"merged {added} new word(s); dictionary now has {len(d)} entries")


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    cmd = sys.argv[1]
    if cmd == "missing":
        cmd_missing(sys.argv[2:])
    elif cmd == "merge":
        cmd_merge(sys.argv[2:])
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
